//example data

import { Task } from "./models/Task";

const mockTasksData: Task[] = [
  {
    taskId: "1",
    priority: "low",
    hasReminder: true,
    reminderDateTime: new Date("2023-04-10T14:30:00"),
    createdDateTime: new Date("2023-04-06T09:00:00"),
    title: "Finish TypeScript tutorial",
    progress: 50,
    content: "Complete the final section on advanced types",
    category: "Learning",
    dueDateTime: new Date("2023-04-20T23:59:59"),
    isCompleted: false,
    completedDateTime: null,
  },
  {
    taskId: "2",
    priority: "low",
    hasReminder: true,
    reminderDateTime: new Date("2023-04-15T14:30:00"),
    createdDateTime: new Date("2023-04-10T09:00:00"),
    title: "Finish TypeScript tutorial",
    progress: 50,
    content: "Complete the final section on advanced types",
    category: "Learning",
    dueDateTime: new Date("2023-04-20T23:59:59"),
    isCompleted: false,
    completedDateTime: new Date("2023-04-10T22:59:59"),
  },
  {
    taskId: "3",
    priority: "medium",
    hasReminder: false,
    reminderDateTime: null,
    createdDateTime: new Date("2023-04-11T11:30:00"),
    title: "Send email to client",
    progress: 0,
    content: "Follow up on project status",
    category: "Work",
    dueDateTime: new Date("2023-04-12T17:00:00"),
    isCompleted: false,
    completedDateTime: new Date("2023-04-09T21:59:59"),
  },
  {
    taskId: "4",
    priority: "high",
    hasReminder: true,
    reminderDateTime: new Date("2023-04-13T10:00:00"),
    createdDateTime: new Date("2023-04-08T15:00:00"),
    title: "Buy groceries",
    progress: 100,
    content: "Milk, bread, eggs, cheese, fruit, vegetables",
    category: "Personal",
    dueDateTime: new Date("2023-04-15T23:59:59"),
    isCompleted: true,
    completedDateTime: new Date("2023-04-10T22:59:59"),
  },
  {
    taskId: "5",
    priority: "low",
    hasReminder: false,
    reminderDateTime: new Date(),
    createdDateTime: new Date(),
    title: "Complete project proposal",
    progress: 0,
    content: "Write a proposal for the new project.",
    category: "Work",
    dueDateTime: new Date("2023-04-30T23:59:59"),
    isCompleted: false,
    completedDateTime: new Date("2023-04-09T23:59:59"),
  },
  {
    taskId: "6",
    priority: "medium",
    hasReminder: true,
    reminderDateTime: new Date("2023-04-15T10:00:00"),
    createdDateTime: new Date(),
    title: "Buy groceries",
    progress: 50,
    content: "Milk, bread, eggs, and cheese",
    category: "Personal",
    dueDateTime: new Date("2023-04-15T23:59:59"),
    isCompleted: false,
    completedDateTime: new Date("2023-04-08T23:59:59"),
  },
  {
    taskId: "7",
    priority: "high",
    hasReminder: false,
    reminderDateTime: new Date(),
    createdDateTime: new Date(),
    title: "Read book",
    progress: 25,
    content: "Finish reading 'To Kill a Mockingbird'",
    category: "Personal",
    dueDateTime: new Date("2023-04-15T23:59:59"),
    isCompleted: false,
    completedDateTime: new Date("2023-04-07T00:59:59"),
  },
  {
    taskId: "8",
    priority: "low",
    hasReminder: true,
    reminderDateTime: new Date("2023-04-12T09:00:00"),
    createdDateTime: new Date(),
    title: "Complete task manager app",
    progress: 100,
    content: "Finish building the task manager app with React and Node.js",
    category: "Work",
    dueDateTime: new Date("2023-04-30T23:59:59"),
    isCompleted: true,
    completedDateTime: new Date("2023-04-06T10:59:59"),
  },
  {
    taskId: "9",
    priority: "medium",
    hasReminder: false,
    reminderDateTime: new Date(),
    createdDateTime: new Date(),
    title: "Take out the trash",
    progress: 10,
    content: "Take out the trash and recycle",
    category: "Personal",
    dueDateTime: new Date("2023-04-12T23:59:59"),
    isCompleted: true,
    completedDateTime: new Date("2023-03-05T10:59:59"),
  },
  {
    taskId: "10",
    priority: "high",
    hasReminder: true,
    reminderDateTime: new Date("2023-04-13T14:00:00"),
    createdDateTime: new Date(),
    title: "Go for a walk",
    progress: 100,
    content: "Take a walk around the park",
    category: "Personal",
    dueDateTime: new Date("2023-04-13T23:59:59"),
    isCompleted: true,
    completedDateTime: new Date("2023-03-06T09:59:59"),
  },
  {
    taskId: "11",
    priority: "low",
    hasReminder: false,
    reminderDateTime: new Date(),
    createdDateTime: new Date(),
    title: "Prepare presentation",
    progress: 10,
    content: "Create a presentation for the client meeting",
    category: "Work",
    dueDateTime: new Date("2023-04-18T23:59:59"),
    isCompleted: false,
    completedDateTime: new Date("2023-02-05T08:59:59"),
  },
];

export default mockTasksData;
